export const TOGGLE_HAMBURGER = 'TOGGLE_HAMBURGER';
export const TOGGLE_SEARCH_MODAL = 'TOGGLE_SEARCH_MODAL';

export const GET_POPULAR_MOVIES_INIT = 'GET_POPULAR_MOVIES_INIT';
export const GET_POPULAR_MOVIES_SUCCESS = 'GET_POPULAR_MOVIES_SUCCESS';
export const GET_POPULAR_MOVIES_ERROR = 'GET_POPULAR_MOVIES_ERROR';

export const SEARCH_MOVIES_INIT = 'SEARCH_MOVIES_INIT';
export const SEARCH_MOVIES_SUCCESS = 'SEARCH_MOVIES_SUCCESS';
export const SEARCH_MOVIES_ERROR = 'SEARCH_MOVIES_ERROR';
